### ISSUE TITLE
License in README does not fit

### ISSUE THREAD

**Issue by pascal-roth** [isaac-orbit/orbit.ext_template#4]
The License in the README has to be changed to MIT. Also there it should be referenced to the orbit-developers.

Generally, for the issues, we can adopt the same template as orbit. Can be configured by copying the files under .github.

**Comment by nburger-bdai** [comment]
Nice! Will add the `.github` folder for this.

Regarding the license, I don't fully understand why we want to switch from BSD-3 to MIT. In Orbit it is BSD-3...

**Comment by pascal-roth** [comment]
You can correct me if I am wrong but as far as I remember, BSD-3 is more strict than MIT. E.g. when you use orbit code, you always have to copy the header whereas with MIT you can really do what you want and don't need to copy it. For own build extensions, I don't think that we should enforce the copying of header and so on
