### ISSUE TITLE
VS code setting mismatch from README

### ISSUE THREAD

**Issue by junja94** [isaac-orbit/orbit.ext_template#9]
Hi, 

I'm trying to use this template and found out that the default interpreter path here :https://github.com/isaac-orbit/orbit.ext_template/blob/main/.vscode/tools/settings.template.json#L68

is different from what you wrote in the README:
"python.defaultInterpreterPath": "${env:ISAACSIM_PATH}/python.sh"

Could you check and update them?

**Comment by nburger-bdai** [comment]
Good catch and thanks for letting us know. We are addressing this by now setting Isaac Sim's bundled Python per default (with `${env:ORBIT_PATH}/_isaac_sim/python.sh`) and prompting the user to set their own path if required. PR is out [here](https://github.com/isaac-orbit/orbit.ext_template/pull/11).
